name: pyLint

on:
  push:
  workflow_dispatch:

jobs:
  pyLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
  